{ den, ... }: {
  den.aspects.kanata = {
    nixos = { pkgs, lib, ... }: {
      environment.systemPackages = [
        pkgs.kanata-with-cmd
      ];
      services = {
        kanata = {
          enable = true;
          keyboards = {
            internalKeyboard = {
              devices = [];
              extraDefCfg = "process-unmapped-keys yes";
              config = ''
                ;; Kanata configuration — generated by KanataUI 2026.7.19.3
                ;; https://github.com/jtroo/kanata

                (defsrc
                  grv tab e r t y u i o p [ caps s d f g h j k l ; ' z x c v b n m , . / ralt rctl IntlBackslash
                )
                
                (deflayer base
                  ' @base-tab f p g BracketLeft j l u y Slash @base-caps r s @base-f d Quote h n e i o x c v b Backslash Semicolon k m , . @base-ralt @base-rctl z
                )

                (deflayer commands
                  _ _ _ _ _ _ _ _ ↑ _ _ _ _ (multi lctl c) (multi lctl v) _ _ _ ← ↓ → ret _ _ _ (macro esc lsft / w) _ _ _ _ _ _ _ _ _ 
                )

                (deflayer sym
                  _ _ _ _ _ _  _ BracketRight Backslash _ _ _ _ _ _ _ grv - = Slash _ _ _ _ _ _ _ , ' _ _ _ _ _ _ 
                )

                (deflayer qwerty
                  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ (layer-toggle base) _ _ 
                )

                (defalias
                  base-tab (tap-hold 200 200 tab lsft)
                  base-caps (tap-hold 200 200 bspc (layer-while-held commands))
                  base-f (tap-hold 200 200 t (layer-while-held sym))
                  base-ralt (layer-toggle qwerty)
                  base-rctl (macro kp1 kp4 143 kp7 119 kp2 143 kp5 111 kp8 105 kprt 208)
                )
              '';
            };
          };
        };
      };
    };
  };
}
